### ISSUE TITLE
[BUG] The xp cost when upgrading a skill isn't right

### ISSUE THREAD

**Issue by werff** [InfinityStudio/GokiStats#1]
Let me explain.

When I upgrade one skill (after upgrading others) it cost's more tan the writen cost.
I don't know if it's a bug or an intended feature.

Also it appears that the xp number below is either wrong or something

**Comment by werff** [comment]
Video Proof
https://www.youtube.com/watch?v=uJPrvD-ykeA&feature=youtu.be

**Comment by ci010** [comment]
he meant "your are right" and "it's a bug"

**Comment by NanamiArihara** [comment]
Minecraft 1.8+ uses new behaviour to calculate experiences, it shouldn't be buggy now.
