### ISSUE TITLE
Literally cant die

### ISSUE THREAD

**Issue by CrazyHoneyBird** [InfinityStudio/GokiStats#14]
When I add this mod nothing can kill me and /kill doesn't work. I cant take dmg in any way shape of form, any help is appreciated. I'm using the forge version forge-14.23.4.27.45

**Comment by NanamiArihara** [comment]
Do you have any stat enabled?

**Comment by CrazyHoneyBird** [comment]
I have leveled up with the xp in game but that's about it. I tried making a new world with the mod by itself and I was still invincible. Is there a config I need to change?

**Comment by SeanChengN** [comment]
The last usable version is 1.1.2

**Comment by NanamiArihara** [comment]
WTF I have a huge config upgrade

**Comment by SeanChengN** [comment]
I deleted all old config, and started a new world, I still can't get hurt.

**Comment by NanamiArihara** [comment]
It's a bug of Roll stat.

**Comment by NanamiArihara** [comment]
https://github.com/InfinityStudio/GokiStats/commit/b6801565ec530e9f84b4997253cbca4411e6971e#diff-522283d5987c29afdaf7cc5f0d3f7e83L246
If you don't have roll enabled, this is always true since

**Comment by CrazyHoneyBird** [comment]
Is there anything I can do? I deleted the roll stat out of my config and it is still bugged for me.

**Comment by CrazyHoneyBird** [comment]
Sorry for my ignorance but how do I disable it?

**Comment by NanamiArihara** [comment]
dammmmmmn see latest commit
