### ISSUE TITLE
#IhaveProblem

### ISSUE THREAD

**Issue by TmeansTERMINATOR** [InfinityStudio/GokiStats#19]
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time:
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from gokiStats (gokistats)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
    at com.google.gson.Gson.fromJson(Gson.java:887)
    at com.google.gson.Gson.fromJson(Gson.java:852)
    at com.google.gson.Gson.fromJson(Gson.java:801)
    at net.infstudio.goki.common.config.ConfigManager.loadConfig(ConfigManager.java:80)
    at net.infstudio.goki.common.config.ConfigManager.reloadConfig(ConfigManager.java:95)
    at net.infstudio.goki.common.config.Configurable.reloadConfig(Configurable.java:22)
    at java.util.ArrayList.forEach(Unknown Source)
    at net.infstudio.goki.GokiStats.preInit(GokiStats.java:71)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
    at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
    ... 43 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_181, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 453021440 bytes (432 MB) / 1021444096 bytes (974 MB) up to 3168927744 bytes (3022 MB)
  JVM Flags: 3 total; -Xincgc -Xms1G -Xmx3G
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.4.2759 84 mods loaded, 84 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                    | Version              | Source                                          | Signature                                |
       |:----- |:--------------------- |:-------------------- |:----------------------------------------------- |:---------------------------------------- |
       | UCH   | minecraft             | 1.12.2               | minecraft.jar                                   | None                                     |
       | UCH   | mcp                   | 9.42                 | minecraft.jar                                   | None                                     |
       | UCH   | FML                   | 8.0.99.99            | forge-1.12.2-14.23.4.2759-universal.jar         | None                                     |
       | UCH   | forge                 | 14.23.4.2759         | forge-1.12.2-14.23.4.2759-universal.jar         | None                                     |
       | UCH   | creativecoredummy     | 1.0.0                | minecraft.jar                                   | None                                     |
       | UCH   | itemphysic            | 1.4.0                | minecraft.jar                                   | None                                     |
       | UCH   | foamfixcore           | 7.7.4                | minecraft.jar                                   | None                                     |
       | UCH   | randompatches         | 1.12.2-1.5.0.4       | randompatches-1.12.2-1.5.0.4.jar                | None                                     |
       | UCH   | uncraftingtable       | 1.8-beta6            | [1.12]UncraftingTable-1.8-beta6.jar             | None                                     |
       | UCH   | aiimprovements        | 0.0.1.3              | AIImprovements-1.12-0.0.1b3.jar                 | None                                     |
       | UCH   | backpacks16840        | 3.5.2                | backpacks+1.12.2+-+3.5.2.jar                    | None                                     |
       | UCH   | jei                   | 4.12.0.215           | jei_1.12.2-4.12.0.215.jar                       | None                                     |
       | UCH   | base                  | 3.10.0               | base-1.12.2-3.10.0.jar                          | None                                     |
       | UCH   | battletowers          | 1.6.3                | BattleTowers-1.12.2.jar                         | None                                     |
       | UCH   | betterthanmending     | 1.1.1                | BetterThanMending-1.1.1.jar                     | None                                     |
       | UCH   | bibliocraft           | 2.4.5                | BiblioCraft[v2.4.5][MC1.12.2].jar               | None                                     |
       | UCH   | biomesoplenty         | 7.0.1.2399           | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar   | None                                     |
       | UCH   | camera                | 1.0.2                | camera-1.0.2.jar                                | None                                     |
       | UCH   | ceanimals             | 1.4.1                | ceanimals-1.12.2-1.4.1.jar                      | None                                     |
       | UCH   | chameleon             | 1.12-4.1.3           | Chameleon-1.12-4.1.3.jar                        | None                                     |
       | UCH   | codechickenlib        | 3.2.1.351            | CodeChickenLib-1.12.2-3.2.1.351-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCH   | chickenchunks         | 2.4.1.73             | ChickenChunks-1.12.2-2.4.1.73-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCH   | chunkpregenerator     | 1.8                  | Chunk+Pregenerator+V1.12-1.8.1.jar              | None                                     |
       | UCH   | clumps                | 3.1.1                | Clumps-3.1.1.jar                                | None                                     |
       | UCH   | creativecore          | 1.9.9                | CreativeCore_v1.9.29_mc1.12.2.jar               | None                                     |
       | UCH   | forgecreeperheal      | 1.3.0                | creeperheal-1.12-1.3.1.jar                      | None                                     |
       | UCH   | epicsiegemod          | 13.162               | EpicSiegeMod-13.162.jar                         | None                                     |
       | UCH   | extrautils2           | 1.0                  | extrautils2-1.12-1.8.5.jar                      | None                                     |
       | UCH   | fastleafdecay         | v14                  | FastLeafDecay-v14.jar                           | None                                     |
       | UCH   | foamfix               | 0.10.1-1.12.2        | foamfix-0.10.1-1.12.2.jar                       | None                                     |
       | UCH   | forgemultipartcbe     | 2.5.0.71             | ForgeMultipart-1.12.2-2.5.0.71-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCH   | microblockcbe         | 2.5.0.71             | ForgeMultipart-1.12.2-2.5.0.71-universal.jar    | None                                     |
       | UCH   | minecraftmultipartcbe | 2.5.0.71             | ForgeMultipart-1.12.2-2.5.0.71-universal.jar    | None                                     |
       | UCEE  | gokistats             | @version@            | gokiStats-1.2.3.1.jar                           | None                                     |
       | UC    | ichunutil             | 7.1.4                | iChunUtil-1.12.2-7.1.4.jar                      | None                                     |
       | UC    | gravitygun            | 7.0.0                | GravityGun-1.12.2-7.0.1.jar                     | None                                     |
       | UC    | hammercore            | 2.0.2.1              | HammerCore-1.12.2-2.0.2.1.jar                   | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | UC    | harvest               | 1.12-1.2.6-18        | Harvest-1.12-1.2.6-18.jar                       | None                                     |
       | UC    | speedsterheroes       | 1.12.2-2.0.7         | SpeedsterHeroes-1.12.2-2.0.7.jar                | None                                     |
       | UC    | lucraftcore           | 1.12.2-2.2.6         | LucraftCore-1.12.2-2.2.6.jar                    | None                                     |
       | UC    | heroesexpansion       | 1.12.2-1.1.6         | HeroesExpansion-1.12.2-1.1.6.jar                | None                                     |
       | UC    | improvableskills      | 3.5.2r               | ImprovableSkills_1.12.2-3.5.2r.jar              | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | UC    | ic2                   | 2.8.97-ex112         | industrialcraft-2-2.8.97-ex112.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
       | UC    | infernalmobs          | 1.7.5                | InfernalMobs-1.12.2.jar                         | None                                     |
       | UC    | ironchest             | 1.12.2-7.0.46.831    | ironchest-1.12.2-7.0.46.831.jar                 | None                                     |
       | UC    | journeymap            | 1.12.2-5.5.2         | journeymap-1.12.2-5.5.2.jar                     | None                                     |
       | UC    | lex                   | 1.0.8                | LibEx-1.12.2-1.0.8.jar                          | None                                     |
       | UC    | lootbags              | 2.5.6                | LootBags-1.12.2-2.5.6.jar                       | None                                     |
       | UC    | lunatriuscore         | 1.2.0.42             | LunatriusCore-1.12.2-1.2.0.42-universal.jar     | None                                     |
       | UC    | mantle                | 1.12-1.3.2.24        | Mantle-1.12-1.3.2.24.jar                        | None                                     |
       | UC    | mcjtylib_ng           | 3.0.3                | mcjtylib-1.12-3.0.3.jar                         | None                                     |
       | UC    | meecreeps             | 1.2.1                | meecreeps-1.12-1.2.1.jar                        | None                                     |
       | UC    | minecolonies          | 1.12.2-0.9.2-RELEASE | minecolonies-1.12.2-0.9.2-RELEASE-universal.jar | None                                     |
       | UC    | multimine             | 1.6.0                | MultiMine-1.12.2.jar                            | None                                     |
       | UC    | nex                   | 2.0.8                | NetherEx-1.12.2-2.0.8.jar                       | None                                     |
       | UC    | recipehandler         | 0.11                 | NoMoreRecipeConflict-0.11(1.12.2).jar           | None                                     |
       | UC    | omlib                 | 3.0.1-162            | omlib-1.12.2-3.0.1-162.jar                      | None                                     |
       | UC    | openmodularturrets    | 3.0.1-264            | openmodularturrets-1.12.2-3.0.1-264.jar         | None                                     |
       | UC    | oreexcavation         | 1.4.123              | OreExcavation-1.4.123.jar                       | None                                     |
       | UC    | outfox                | 0.1.2                | outfox-0.1.2-mc1.12.2.jar                       | None                                     |
       | UC    | playerrevive          | 1.0                  | PlayerRevive_v1.2.16_mc1.12.2.jar               | None                                     |
       | UC    | rftools               | 7.55                 | rftools-1.12-7.55.jar                           | None                                     |
       | UC    | roguelike             | 1.8.0                | RoguelikeDungeons-1.12.2-1.8.0.jar              | None                                     |
       | UC    | silentlib             | 3.0.1                | SilentLib-1.12.2-3.0.1-145.jar                  | None                                     |
       | UC    | scalinghealth         | 1.3.26               | ScalingHealth-1.12.2-1.3.26-127.jar             | None                                     |
       | UC    | sdrones               | 1.3.1                | sdrones-1.3.1.jar                               | None                                     |
       | UC    | sereneseasons         | 1.2.6                | SereneSeasons-1.12.2-1.2.6-universal.jar        | None                                     |
       | UC    | stackie               | 1.6.0.48             | Stackie-1.12.2-1.6.0.48-universal.jar           | None                                     |
       | UC    | storagedrawers        | 1.12-5.3.5           | StorageDrawers-1.12.2-5.3.7.jar                 | None                                     |
       | UC    | sync                  | 7.0.2                | Sync-1.12.2-7.0.2.jar                           | None                                     |
       | UC    | thutcore              | 5.19.7               | thutcore-1.12.2-5.19.7.jar                      | None                                     |
       | UC    | thutcore_compat       | 1.0                  | thutcore-1.12.2-5.19.7.jar                      | None                                     |
       | UC    | thuttech              | 6.1.4                | thuttech-1.12.2-6.1.4.jar                       | None                                     |
       | UC    | tickratechanger       | 1.0.14               | TickrateChanger-1.0.14.jar                      | None                                     |
       | UC    | torched               | 7.0.0                | Torched-1.12.2-7.0.0.jar                        | None                                     |
       | UC    | tpmod                 | 1.12.2-0.3           | TorchPlaceMod-1.12.2-0.3.jar                    | None                                     |
       | UC    | toughasnails          | 3.1.0.128            | ToughAsNails-1.12.2-3.1.0.128-universal.jar     | None                                     |
       | UC    | twilightforest        | 3.8.654              | twilightforest-1.12.2-3.8.654-universal.jar     | None                                     |
       | UC    | vanillafix            | 1.0.9-97             | VanillaFix-1.0.9-97.jar                         | None                                     |
       | UC    | wanionlib             | 1.12.2-1.5           | WanionLib-1.12.2-1.5.jar                        | None                                     |
       | UC    | wawla                 | 2.5.257              | Wawla-1.12.2-2.5.257.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UC    | wrcbe                 | 2.3.1                | WR-CBE-1.12.2-2.3.1.29-universal.jar            | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UC    | thebetweenlands       | 3.3.11               | TheBetweenlands-3.3.11-universal.jar            | 38067d6878811efb38b6a045521cfd80b9b60b38 |
       | UC    | unidict               | 1.12.2-2.7b          | UniDict-1.12.2-2.7b.jar                         | None                                     |
  Loaded coremods (and transformers): RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
                                        pw.prok.realbench.asm.RBTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.9-97.jar)
                                        
                                      CreativePatchingLoader (CreativeCore_v1.9.29_mc1.12.2.jar)
                                        
                                      HCASM (HammerCore-1.12.2-2.0.2.1.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.6-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      TickrateChanger (TickrateChanger-1.0.14.jar)
                                        me.guichaguri.tickratechanger.TickrateTransformer
                                      MMFMLCorePlugin (MultiMine-1.12.2.jar)
                                        atomicstryker.multimine.common.fmlmagic.MMTransformer
                                      LucraftCoreCoreMod (LucraftCore-1.12.2-2.2.6.jar)
                                        lucraft.mods.lucraftcore.core.LCTransformer
                                      ItemPatchingLoader (ItemPhysic_Full_1.4.16_mc1.12.2.jar)
                                        com.creativemd.itemphysic.ItemTransformer
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.11-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.10.1-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      RandomPatches (randompatches-1.12.2-1.5.0.4.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      BCModPlugin (backpacks+1.12.2+-+3.5.2.jar)
                                        brad16840.core.ClassTransformer
  Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
                           OreDictionary Info: Registered 301 names; 489 stacks.
                           Pastebin Connection: Okay.
  Suspected Mods: gokiStats (gokistats)
  Profiler Position: N/A (disabled)
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)

**Comment by NanamiArihara** [comment]
Please delete files or folders started with "goki" in your config dir, problem is caused by incompatible config version.

**Comment by NanamiArihara** [comment]
Also, post crash-report on pastebin next time.

**Comment by TmeansTERMINATOR** [comment]
Thank yo human
