### ISSUE TITLE
【功能需求】死亡丢失，等级撤回

### ISSUE THREAD

**Issue by SeanChengN** [InfinityStudio/GokiStats#21]
【死亡丢失】
当前功能：死亡时丢失所有技能等级，难度太大。
期望功能：死亡时丢失部分等级（配置文件修改，可禁用）。比如：丢失5级或丢失20%。

【等级撤回】
当前功能：可以随意撤回已升级的技能。
期望功能：设置可撤回的最大等级（配置文件修改，可禁用），比如：最多只能撤回10级。

**Comment by NanamiArihara** [comment]
死亡丢失弄了，撤回最大等级由于涉及到NBT，我可能以后还得重写这部分同步

**Comment by SeanChengN** [comment]
谢谢，现在敢下矿洞了，敢肛一群怪了
