### ISSUE TITLE
GokiStats conflict with ProjectE

### ISSUE THREAD

**Issue by JaklMUSIC** [InfinityStudio/GokiStats#23]
When using ProjectE's Swiftwolf Rending Gale Projectile, upon the projectile striking a mob, the game will crash. This is reproducible on both clients and servers.

Steps to reproduce:
1) Install ProjectE (Latest) and Goki Stats (Latest)
2) Launch game and get a Swiftwolf's Rending Gale from ProjectE, and have fuel (coal, or a charged Klein Star) in your inventory.
3) Press R, with the Swiftwolf in hand, to launch a projectile at a mob.
4) Crash.

I believe this happens because GokiStats affects movement in some aspect, and this projectE projectile is supposed to launch mobs into the air / backwards. Movement A + Movement B = Crash ??
[crash-2018-09-13_02.03.26-server.txt](https://github.com/InfinityStudio/GokiStats/files/2377892/crash-2018-09-13_02.03.26-server.txt)

**Comment by ci010** [comment]
Just a quick looks.

From the projectE [EntitySWRGProjectile](https://github.com/sinkillerj/ProjectE/blob/e310ed5244e69a2c20eadfc839f781151363469a/src/main/java/moze_intel/projecte/gameObjs/entity/EntitySWRGProjectile.java#L98).
It passes a null as attacker. The goki crashes at this point.

I did a quick fix at commit [8eb1d40ecc95205a0cf9803f9019cb1f0b4c0155](https://github.com/InfinityStudio/GokiStats/commit/8eb1d40ecc95205a0cf9803f9019cb1f0b4c0155)

Please wait @NanamiArihara to check if this works.

**Comment by NanamiArihara** [comment]
Same with #20
