### ISSUE TITLE
【问题反馈】打开存档时等级消失

### ISSUE THREAD

**Issue by SeanChengN** [InfinityStudio/GokiStats#27]
MOD版本：1.2.5.1
【问题重现】
打开存档时等级为0，点击一下会恢复，之前版本没有这个问题。
![2](https://user-images.githubusercontent.com/20624068/45592961-88c6a280-b9ad-11e8-879a-47ea27193114.gif)
注：有图，加载缓慢

**Comment by NanamiArihara** [comment]
我在载入世界的时候没有同步数据...
________________________________
