### ISSUE TITLE
Losing Skills on Death DESPITE Having This Set as "false" in the config

### ISSUE THREAD

**Issue by FriendlyGamer** [InfinityStudio/GokiStats#28]
As the title suggest even though the config says it's false, I lost ALL of my skills on death.  
See attached... 
![screenshot from 2018-09-18 12-05-58](https://user-images.githubusercontent.com/38051855/45700851-9ad64b80-bb3b-11e8-83d4-ab508cde6f96.png)

**Comment by FriendlySurvival** [comment]
Upon upgrading a skill it's apparently "came right back" which make this bug even stranger...

**Comment by FriendlySurvival** [comment]
After more in depth investigation while playing with this mod, this "bug" or at least issue with the mod DOES happens upon every log in or at least after every few hours intervals of being on and off of a multiplayer server. As I said before, it will "return" all skills once a skill is indeed upgraded. But it will not retain the skill set once you log out and back in after at least some time.
