### ISSUE TITLE
当死亡后等级就全部变0了

### ISSUE THREAD

**Issue by zsn741656478** [InfinityStudio/GokiStats#35]
"Death Loss"=false
这里已经是false了依然会损失等级，但是不知为啥每次点进去界面后点一下又会恢复，感觉怪怪的。

还有这个配置是什么意思？
    support {
        D:"Bowmanship Limit"=20.0
        D:"Reaper Limit"=20.0
    }

**Comment by NanamiArihara** [comment]
反弹伤害的大小。
