### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Dkpita2** [InfinityStudio/GokiStats#39]
When cooking skill increases, cooked food inside the furnace does not stack.

**Comment by NanamiArihara** [comment]
Did you feel the item has produced more than normal rate? Or simply ineffective

**Comment by Dkpita2** [comment]
If you cook 10 of meat for example, the furnace cook 1 and until you do not pick up the meat, it do not cook anymore. It stays locked after cooking 1.

**Comment by NanamiArihara** [comment]
Strange, I will test it on my local machine

________________________________

**Comment by Dkpita2** [comment]
My apologies, it was another mod that caused the error
