### ISSUE TITLE
Fast Sinking when in Water

### ISSUE THREAD

**Issue by Fortist** [InfinityStudio/GokiStats#4]
Maybe it's a combination of mods but whenever I get into water, I sink near instantly.

**Comment by NanamiArihara** [comment]
Level 1?

**Comment by LordHarkon** [comment]
No level. It happens to me too. And not only that, I am walking really fast on the floor underwater. It's definitely the mod because before I added it I was walking normally.

**Comment by NanamiArihara** [comment]
@LordHarkon @Fortist Please try for the latest release and report if this problem still occurs.

**Comment by Fortist** [comment]
It works but with points in Fast Swimming it happens, but I guess thats what it's for.

**Comment by NanamiArihara** [comment]
It's a bug of Minecraft engine, won't fix until 1.13.
