### ISSUE TITLE
比较关键性的改动，提高兼容性

### ISSUE THREAD

**Issue by Abo233** [InfinityStudio/GokiStats#40]
1.可不可以把按键删除，改成用指令打开界面，设置一个简单指令比如说/gs level

2.或者改成用书右键才能打开界面                                                                                              
 （就像 Improvable Skills 3一样用本技能书打开，GUI就不要了兼容性有点差）

注：建议就改成第二种

**Comment by ci010** [comment]
@NanamiArihara

**Comment by NanamiArihara** [comment]
有那么一丁点道理

**Comment by NanamiArihara** [comment]
看了一眼还是用指令吧
