### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by LokyLive** [InfinityStudio/GokiStats#5]
A pretty cool mod !
 
Could you add on cfg file a setting to active/unactive specific skill and a setting to change multiplier for each skill ?

**Comment by NanamiArihara** [comment]
For _each_ skill? Seems like a good idea.

**Comment by simon300000** [comment]
Use a generator?

发自我的 iPhone

**Comment by NanamiArihara** [comment]
Rewriting config system, this feature will be pushed in next update.
