### ISSUE TITLE
1.12.2 Crash after closing stats menu

### ISSUE THREAD

**Issue by Chubzik1** [InfinityStudio/GokiStats#57]
When i press the button to open stats menu, it crashes instantly, but if i hold the button, it wont crash until i release the button

crash report:
https://pastebin.com/HJ6SubJD

**Comment by PROJonYz** [comment]
Same here, trying to add to my modpack, but it doesnt work, if i open menu, insta crashing minecraft, i dont know what problem it is, but im trying to install other versions of Goki Stats, if i fix this, ill let you know it!

**Comment by Chubzik1** [comment]
looks like its fixed now, thanks.
