### ISSUE TITLE
空手攻击伤害bug的反馈

### ISSUE THREAD

**Issue by oakfisher** [InfinityStudio/GokiStats#58]
1.12.2安装了本mod后，徒手攻击伤害就翻倍了( 没有点拳击手技能) ,
同时这个翻倍对力量buff也有效果,导致玩家不点拳击技能,也能在力量2药水的buff下，空手打出14点高伤害
(而且空手攻速非常快)

1.2.8.2版本依然有这个问题,

**Comment by LasmGratel** [comment]
再试试
