### ISSUE TITLE
Can we have per skill config, or at least get config for Roll?

### ISSUE THREAD

**Issue by No3371** [InfinityStudio/GokiStats#64]
Roll is kinda op for my modpack, I'd like to adjust it's effect or xp cost.

If we have control over every skill, It'd be very easy for modpacks to integrate the mod and balance it :D

**Comment by LasmGratel** [comment]
good suggestion

**Comment by Ja-spec** [comment]
Popped in here to ask this. Getting tons of extra hearts makes my back super unbalanced, would like a way to limit this

**Comment by LasmGratel** [comment]
Now you can set max level limit per stat in `serverconfig` folder

**Comment by No3371** [comment]
Thanks 💯 , I will wait for 1.16.3 version before I udpate my pack next time.

**Comment by Ja-spec** [comment]
is this for 1.16.3 or not yet. I loaded up the game but no config folder :(
