### ISSUE TITLE
[1.16+] Suggestion: Custom skillloss death penalty.

### ISSUE THREAD

**Issue by Cixon** [InfinityStudio/GokiStats#66]
Instead of losing all skilltree levels when players die _(default setup)_, how bout allowing modpack/server owners to adjust how much skill levels are lost upon death?

For example, when a player dies:
# 0 ~ 50 random points per death

**Comment by LasmGratel** [comment]
You can change `loseStatsMultiplier` in the config or set them per stat

**Comment by Cixon** [comment]
yes but ranges are
0.0 ~ 1.0

So when players die, they lose all of everything.
Where as, losing a little by little after every death is the goal.
