### ISSUE TITLE
[1.16.5] CLIENT CRASH | NullPointerException: Why You Hate Latest Forge? :(

### ISSUE THREAD

**Issue by Cixon** [InfinityStudio/GokiStats#67]
**Describe the bug**
Client crashes when trying to open the GokiStats GUI in a single-player environment on later versions of forge.
 _(did not test on multi-player.)_

**To Reproduce**
1.) Update Client to forge 1.16.5 version 36.0.42
2.) Install latest GokiStats _(version 1.2.13)_.
3.) Load any fresh new world.
4.) Attempt to open GUI.

### LOGS
[latest.log](https://github.com/InfinityStudio/GokiStats/files/6040091/latest.log)   **Line 223**
[debug.log](https://github.com/InfinityStudio/GokiStats/files/6040092/debug.log)  **Line 841**
[crash-2021-02-24_19.58.44-client.txt](https://github.com/InfinityStudio/GokiStats/files/6040093/crash-2021-02-24_19.58.44-client.txt)

**Comment by Cixon** [comment]
I love this mod, it's one of a kind!
Please fix when you get the chance.
:)

**Comment by LasmGratel** [comment]
GuiCompatibilityHelper is planned to be removed.

**Comment by Cixon** [comment]
Understood. I hope to see fix soon!
